name: abc_farm_frontend
description: ABC Farm (frontend-only) app
publish_to: 'none'
version: 1.0.0+1
environment:
  sdk: ">=2.17.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  shared_preferences: ^2.1.0
  camera: ^0.10.5+9
  flutter_localizations:
    sdk: flutter
  intl: ^0.20.2
  qr_flutter: ^4.1.0
  crypto: ^3.0.3
  pointycastle: ^3.7.3
  http: ^1.1.0
  mobile_scanner: ^3.0.0
  image_picker: ^1.0.7
  firebase_core: ^2.24.2
  firebase_auth: ^4.15.3
  cloud_firestore: ^4.14.0
  encrypt: ^5.0.1
  google_sign_in: ^6.2.1
  fl_chart: ^0.66.1
  pdf: ^3.10.7
  path_provider: ^2.1.3
  geolocator: ^12.0.0
  flutter_local_notifications: ^17.2.2
  timezone: ^0.9.3

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_launcher_icons: ^0.13.1

flutter:
  uses-material-design: true
  generate: true
  assets:
    - assets/images/app_icon.png
    - assets/images/app_logo.png
    - assets/images/Animal ID.png
    - assets/images/cow.png
    - assets/images/buffalo.png
    - assets/images/goat.png
    - assets/images/sheep.png
    - assets/images/pig.png
    - assets/images/poultry.png
    - assets/images/other.png
  fonts:
    - family: NotoSansTamil
      fonts:
        - asset: fonts/NotoSansTamil-Regular.ttf
        - asset: fonts/NotoSansTamil-Bold.ttf
          weight: 700

flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  min_sdk_android: 21
  web:
    generate: true
    image_path: "assets/images/app_logo.png"
    background_color: "#hexcode"
    theme_color: "#hexcode"
  windows:
    generate: true
    image_path: "assets/images/app_logo.png"
    icon_size: 48
  macos:
    generate: true
    image_path: "assets/images/app_logo.png"
